# .cpanel.yml
---
deployment:
    tasks:
        - export NODE_VERSION=16
        - export YARN_VERSION=1.22
        - echo "Using Node $NODE_VERSION and Yarn $YARN_VERSION"
        - source /opt/cpanel/ea-nodejs16/enable
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
        - yarn install
        - yarn build
        - rsync -av --delete build/ /home/your_cpanel_user/public_html/
