export const postData = [
    { id: 1, title: "Campus series highlights", description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio a dolore porro similique, perspiciatis fugit praesentium sequi possimus aspernatur expedita voluptas minima rem voluptate unde esse fugiat id accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit.", isFeatured: false },
    { id: 2, title: "Title goes here", description: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio a dolore porro similique, perspiciatis fugit praesentium sequi possimus aspernatur expedita voluptas minima rem voluptate unde esse fugiat id accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit.", isFeatured: false },
    { id: 3, title: "Here goes the title", description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio a dolore porro similique, perspiciatis fugit praesentium sequi possimus aspernatur expedita voluptas minima rem voluptate unde esse fugiat id accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit.", isFeatured: false },
    { id: 4, title: "The title goes here", description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio a dolore porro similique, perspiciatis fugit praesentium sequi possimus aspernatur expedita voluptas minima rem voluptate unde esse fugiat id accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit.", isFeatured: false },
    { id: 5, title: "Highlights from the national summit", description: "   Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio a dolore porro similique, perspiciatis fugit praesentium sequi possimus aspernatur expedita voluptas minima rem voluptate unde esse fugiat id accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit.", isFeatured: false },
    { id: 6, title: "How to benefit the most from startup bauchi", description: " Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus odio a dolore porro similique, perspiciatis fugit praesentium sequi possimus aspernatur expedita voluptas minima rem voluptate unde esse fugiat id accusantium ? Lorem ipsum dolor sit amet consectetur adipisicing elit.", isFeatured: true },
    { id: 7, title: "Step by step guide to marketting", description: " Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus odio a dolore porro similique, perspiciatis fugit praesentium sequi possimus aspernatur expedita voluptas minima rem voluptate unde esse fugiat id accusantium ? Lorem ipsum dolor sit amet consectetur adipisicing elit.", isFeatured: true },

]